services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./200_infra/www:/usr/share/nginx/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example

    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
